In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import seaborn as sns

In [4]:
df = pd.read_csv("YoutubeCommentsDataSet.csv" , encoding = "latin1")

In [5]:
df.tail()

                                                 Comment Sentiment
18403  i really like the point about engineering tool...  positive
18404  iâve just started exploring this field and t...  positive
18405  excelente video con una pregunta filosÃ³fica p...   neutral
18406  hey daniel just discovered your channel a coup...  positive
18407  this is great focus is key a playful approach ...  positive

In [6]:
df.shape

(18408, 2)

In [7]:
df.columns

Index(['Comment', 'Sentiment'], dtype='str')

In [8]:
df = df[["Comment", "Sentiment"]]

In [9]:
df.isnull().sum()

Comment      44
Sentiment     0
dtype: int64

In [10]:
df['Comment'] = df['Comment'].fillna("no Comment")

In [11]:
df.duplicated().sum()

np.int64(531)

In [12]:
df.drop_duplicates()

                                                 Comment Sentiment
0      lets not forget that apple pay in 2014 require...   neutral
1      here in nz 50 of retailers donât even have c...  negative
2      i will forever acknowledge this channel with t...  positive
3      whenever i go to a place that doesnât take a...  negative
4      apple pay is so convenient secure and easy to ...  positive
...                                                  ...       ...
18403  i really like the point about engineering tool...  positive
18404  iâve just started exploring this field and t...  positive
18405  excelente video con una pregunta filosÃ³fica p...   neutral
18406  hey daniel just discovered your channel a coup...  positive
18407  this is great focus is key a playful approach ...  positive

[17877 rows x 2 columns]

In [13]:
df.duplicated().sum()

np.int64(531)

In [14]:
df = df.drop_duplicates(subset=['Comment'])

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
print(f"spam message : {(df["Sentiment"] == "positive").sum()}")

spam message : 11052

In [17]:
print(f"spam message : {(df["Sentiment"] == "neutral").sum()}")

spam message : 4502

In [18]:
print(f"spam message : {(df["Sentiment"] == "negative").sum()}")

spam message : 2318

In [19]:
df["Comment"] = df["Comment"].str.lower()

In [20]:
df.head(3)

                                             Comment Sentiment
0  lets not forget that apple pay in 2014 require...   neutral
1  here in nz 50 of retailers donât even have c...  negative
2  i will forever acknowledge this channel with t...  positive

In [21]:
import re

In [22]:
df['Comment'] = df['Comment'].apply(lambda x: re.sub(r'[^a-z \s]', '', x))

In [23]:
df.head()

                                             Comment Sentiment
0  lets not forget that apple pay in  required a ...   neutral
1  here in nz  of retailers dont even have contac...  negative
2  i will forever acknowledge this channel with t...  positive
3  whenever i go to a place that doesnt take appl...  negative
4  apple pay is so convenient secure and easy to ...  positive

In [24]:
import nltk

In [25]:
nltk.download("punkt")

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\agraw\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!

True

In [26]:
nltk.download("stopwords")

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\agraw\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

True

In [27]:
nltk.download("wordnet")

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\agraw\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [28]:
from nltk.tokenize import word_tokenize,sent_tokenize

In [29]:
nltk.download("punkt_tab")

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\agraw\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [30]:
from nltk.corpus import stopwords

In [31]:
stopwords = set(stopwords.words('english'))

In [32]:
df['Comment'] = df['Comment'].apply(lambda x : " ".join(
    [words for words in word_tokenize(x) 
     if words not in stopwords]
))

In [33]:
print(df["Comment"][2])

forever acknowledge channel help lessons ideas explanations quite helpful youll sit comfort monitor account growth

In [34]:
import nltk
from nltk.stem import PorterStemmer

In [35]:
stemmer = PorterStemmer()

In [36]:
df['Comment'] = df['Comment'].apply(
    lambda x: " ".join([stemmer.stem(word) for word in x.split()])
)

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [38]:
x = df["Comment"]

In [39]:
y = df["Sentiment"]

In [40]:
tfidf = TfidfVectorizer(max_features=3000)

In [41]:
x_vec = tfidf.fit_transform(x)

In [42]:
x_vec.shape[1]

3000

In [43]:
from sklearn.model_selection import train_test_split

In [44]:
x_train,x_test,y_train,y_test = X_train, X_test, Y_train, Y_test = train_test_split(
    x_vec,
    y,
    test_size=0.20,
    random_state=42
)

In [45]:
from sklearn.naive_bayes import MultinomialNB

In [46]:
model = MultinomialNB()

In [47]:
model.fit(x_train,y_train)

MultinomialNB()

In [48]:
y_pred = model.predict(x_test)

In [49]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [50]:
accuracy = accuracy_score(y_test, y_pred)

In [51]:
print(accuracy_score)

<function accuracy_score at 0x000002C141921BC0>

In [52]:
cm = confusion_matrix(y_test, y_pred)

In [53]:
cm

array([[  76,   37,  349],
       [  23,  251,  645],
       [   9,   89, 2096]])

In [54]:
def predict_comment (Comment):
    cmt = Comment.lower()
    cmt = re.sub(r'[^a-z \s]', " ", cmt)
    token = word_tokenize(cmt)
    token = [w for w in token
            if w not in stopwords]
    tokens = [stemmer.stem(w) for w in token]
    clean_cmt = " ".join(tokens)
    vec = tfidf.transform([clean_cmt])
    result = model.predict(vec)[0]
    prob= model.predict(vec)[0]
    return result, prob

In [55]:
text_cmt="this is nice video and the content is very good i like it"

In [57]:
predict_comment(text_cmt)

(np.str_('positive'), np.str_('positive'))